export const SET_LOADING: 'SET_LOADING' = 'SET_LOADING';

export const GET_INGREDIENTS: 'GET_INGREDIENTS' = 'GET_INGREDIENTS';

export const ADD_INGREDIENT_TO_ORDER: 'ADD_INGREDIENT_TO_ORDER' = 'ADD_INGREDIENT_TO_ORDER';
export const DELETE_INGREDIENT_FROM_ORDER: 'DELETE_INGREDIENT_FROM_ORDER' = 'DELETE_INGREDIENT_FROM_ORDER';
export const SORT_INGREDIENT_IN_ORDER: 'SORT_INGREDIENT_IN_ORDER' = 'SORT_INGREDIENT_IN_ORDER';
export const CLEAR_INGREDIENTS_IN_ORDER: 'CLEAR_INGREDIENTS_IN_ORDER' = 'CLEAR_INGREDIENTS_IN_ORDER';

export const SET_ORDER_DETAILS: 'SET_ORDER_DETAILS' = 'SET_ORDER_DETAILS';
export const CLEAR_ORDER_INFO: 'CLEAR_ORDER_INFO' = 'CLEAR_ORDER_INFO';

export const SET_ERROR_MESSAGE: 'SET_ERROR_MESSAGE' = 'SET_ERROR_MESSAGE';

export const RESET_PASSWORD: 'RESET_PASSWORD' = 'RESET_PASSWORD';
export const LOGIN: 'LOGIN' = 'LOGIN';
export const SET_TOKEN: 'SET_TOKEN' = 'SET_TOKEN';

export const SET_USER: 'SET_USER' = 'SET_USER';
export const CLEAR_USER: 'CLEAR_USER' = 'CLEAR_USER';
export const SET_USER_AUTH: 'SET_USER_AUTH' = 'SET_USER_AUTH';

export const WS_CONNECTION_START: 'WS_CONNECTION_START' = 'WS_CONNECTION_START';
export const WS_CUSTOM_URL_CONNECTION_START: 'WS_CUSTOM_URL_CONNECTION_START' = 'WS_CUSTOM_URL_CONNECTION_START';
export const WS_CONNECTION_SUCCESS: 'WS_CONNECTION_SUCCESS' = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_CLOSED: 'WS_CONNECTION_CLOSED' = 'WS_CONNECTION_CLOSED';
export const WS_CONNECTION_ERROR: 'WS_CONNECTION_ERROR' = 'WS_CONNECTION_ERROR';
export const WS_GET_ORDERS: 'WS_GET_ORDERS' = 'WS_GET_ORDERS';
export const WS_SEND_MESSAGE: 'WS_SEND_MESSAGE' = 'WS_SEND_MESSAGE';
export const WS_CLOSE_CONNECTION: 'WS_CLOSE_CONNECTION' = 'WS_CLOSE_CONNECTION';

export const SET_WS_ORDERS: 'SET_WS_ORDERS' = 'SET_WS_ORDERS';
