export const SET_LOADING_OFF: 'SET_LOADING_OFF' = 'SET_LOADING_OFF';
export const SET_LOADING_ON: 'SET_LOADING_ON' = 'SET_LOADING_ON';

export const GET_INGREDIENTS: 'GET_INGREDIENTS' = 'GET_INGREDIENTS';

export const SET_INGREDIENT_DETAILS: 'SET_INGREDIENT_DETAILS' = 'SET_INGREDIENT_DETAILS';
export const CLEAR_INGREDIENT_DETAILS: 'CLEAR_INGREDIENT_DETAILS' = 'CLEAR_INGREDIENT_DETAILS';

export const ADD_INGREDIENT_TO_ORDER: 'ADD_INGREDIENT_TO_ORDER' = 'ADD_INGREDIENT_TO_ORDER';
export const DELETE_INGREDIENT_FROM_ORDER: 'DELETE_INGREDIENT_FROM_ORDER' = 'DELETE_INGREDIENT_FROM_ORDER';
export const SORT_INGREDIENT_IN_ORDER: 'SORT_INGREDIENT_IN_ORDER' = 'SORT_INGREDIENT_IN_ORDER';
export const CLEAR_INGREDIENTS_IN_ORDER: 'CLEAR_INGREDIENTS_IN_ORDER' = 'CLEAR_INGREDIENTS_IN_ORDER';

export const SET_ORDER_DETAILS: 'SET_ORDER_DETAILS' = 'SET_ORDER_DETAILS';
export const CLEAR_ORDER_INFO: 'CLEAR_ORDER_INFO' = 'CLEAR_ORDER_INFO';

export const SET_ERROR_MESSAGE: 'SET_ERROR_MESSAGE' = 'SET_ERROR_MESSAGE';